# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: eapteka.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\reapteka.proto\x12\x07\x65\x61pteka\"\x14\n\x04\x43ity\x12\x0c\n\x04name\x18\x01 \x01(\t\"g\n\x07Product\x12\x0b\n\x03sku\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x62rand\x18\x03 \x01(\t\x12\r\n\x05price\x18\x04 \x01(\x05\x12\x11\n\tprice_old\x18\x05 \x01(\x05\x12\x10\n\x08\x63\x61tegory\x18\x06 \x01(\t2<\n\tRunParser\x12/\n\nrun_parser\x12\r.eapteka.City\x1a\x10.eapteka.Product\"\x00\x62\x06proto3')



_CITY = DESCRIPTOR.message_types_by_name['City']
_PRODUCT = DESCRIPTOR.message_types_by_name['Product']
City = _reflection.GeneratedProtocolMessageType('City', (_message.Message,), {
  'DESCRIPTOR' : _CITY,
  '__module__' : 'eapteka_pb2'
  # @@protoc_insertion_point(class_scope:eapteka.City)
  })
_sym_db.RegisterMessage(City)

Product = _reflection.GeneratedProtocolMessageType('Product', (_message.Message,), {
  'DESCRIPTOR' : _PRODUCT,
  '__module__' : 'eapteka_pb2'
  # @@protoc_insertion_point(class_scope:eapteka.Product)
  })
_sym_db.RegisterMessage(Product)

_RUNPARSER = DESCRIPTOR.services_by_name['RunParser']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CITY._serialized_start=26
  _CITY._serialized_end=46
  _PRODUCT._serialized_start=48
  _PRODUCT._serialized_end=151
  _RUNPARSER._serialized_start=153
  _RUNPARSER._serialized_end=213
# @@protoc_insertion_point(module_scope)
