# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import eapteka_pb2 as eapteka__pb2


class RunParserStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.run_parser = channel.unary_unary(
                '/eapteka.RunParser/run_parser',
                request_serializer=eapteka__pb2.City.SerializeToString,
                response_deserializer=eapteka__pb2.Product.FromString,
                )


class RunParserServicer(object):
    """Missing associated documentation comment in .proto file."""

    def run_parser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RunParserServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'run_parser': grpc.unary_unary_rpc_method_handler(
                    servicer.run_parser,
                    request_deserializer=eapteka__pb2.City.FromString,
                    response_serializer=eapteka__pb2.Product.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'eapteka.RunParser', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RunParser(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def run_parser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/eapteka.RunParser/run_parser',
            eapteka__pb2.City.SerializeToString,
            eapteka__pb2.Product.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
